substitutions:
  device_name: doorbell-basement-door
  friendly_name: "Doorbell Basement Door"
  api_encryption_key: "secret-api-key"
  ota_password: "secret-ota-password"


# Include the fingerprint doorbell package
packages:
  fingerprint_doorbell: !include github://claudio-walser/esphome-fingerprint-doorbell/fingerprint-doorbell.yaml@main

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${friendly_name} - Wlan"
    password: "12345678"

web_server:
  port: 80

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: ${api_encryption_key}

# Enable OTA updates  
ota:
  - platform: esphome
    password: ${ota_password}

# Logging
logger:
  level: DEBUG
  logs:
    fingerprint_doorbell: DEBUG
