# Fingerprint Doorbell ESPHome Package
# Version 1.0
substitutions:
  device_name: doorbell-basement-door
  friendly_name: "Doorbell Basement Door"
    # API encryption key for Home Assistant
  # Generate with: esphome fingerprint-doorbell.yaml run
  api_encryption_key: "/1//X04nj/HzjNFzVk/KtU1xnmryXWXhpBQnfuXcUug="

  # OTA password for over-the-air updates
  ota_password: "6cf776e37113992a6aba94ff33f82e54"

# External components
external_components:
  - source:
      type: git
      url: https://github.com/claudio-walser/esphome-fingerprint-doorbell
      ref: main
    components: [ fingerprint_doorbell ]

# Required library for fingerprint sensor
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  libraries:
    - "adafruit/Adafruit Fingerprint Sensor Library@^2.1.0"

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Core UART configuration for fingerprint sensor
uart:
  id: uart_fingerprint
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 57600

# Main fingerprint doorbell component
fingerprint_doorbell:
  id: fp_doorbell
  uart_id: uart_fingerprint
  touch_pin: GPIO5
  doorbell_pin: GPIO19
  ignore_touch_ring: false

# Sensors
sensor:
  - platform: fingerprint_doorbell
    fingerprint_doorbell_id: fp_doorbell
    match_id:
      name: "Fingerprint Match ID"
      id: fp_match_id
    confidence:
      name: "Fingerprint Confidence"
      id: fp_confidence

text_sensor:
  - platform: fingerprint_doorbell
    fingerprint_doorbell_id: fp_doorbell
    match_name:
      name: "Fingerprint Match Name"
      id: fp_match_name

binary_sensor:
  - platform: fingerprint_doorbell
    fingerprint_doorbell_id: fp_doorbell
    ring:
      name: "Doorbell Ring"
      id: fp_ring
    finger:
      name: "Finger Detected"
      id: fp_finger

# Logging
logger:
  level: DEBUG
  logs:
    fingerprint_doorbell: DEBUG
