# Fingerprint Doorbell ESPHome Package
# Version 2.0 - Fixed non-blocking implementation

substitutions:
  device_name: doorbell-basement-door
  friendly_name: "Doorbell Basement Door"
  # API encryption key for Home Assistant
  api_encryption_key: "/1//X04nj/HzjNFzVk/KtU1xnmryXWXhpBQnfuXcUug="
  # OTA password for over-the-air updates
  ota_password: "6cf776e37113992a6aba94ff33f82e54"

# External components
external_components:
  - source:
      type: git
      url: https://github.com/claudio-walser/esphome-fingerprint-doorbell
      ref: main
    components: [ fingerprint_doorbell ]
    refresh: 0s

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  libraries:
    - "adafruit/Adafruit Fingerprint Sensor Library@^2.1.0"

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${friendly_name} - Wlan"
    password: "12345678"

web_server:
  port: 80

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: ${api_encryption_key}
  services:
    - service: enroll_fingerprint
      variables:
        finger_id: int
        name: string
      then:
        - lambda: |-
            id(fp_doorbell).enroll_fingerprint(finger_id, name);
    - service: delete_fingerprint
      variables:
        finger_id: int
      then:
        - lambda: |-
            id(fp_doorbell).delete_fingerprint(finger_id);
    - service: delete_all_fingerprints
      then:
        - lambda: |-
            id(fp_doorbell).delete_all_fingerprints();
    - service: rename_fingerprint
      variables:
        finger_id: int
        name: string
      then:
        - lambda: |-
            id(fp_doorbell).rename_fingerprint(finger_id, name);

# Enable OTA updates  
ota:
  - platform: esphome
    password: ${ota_password}

# Fingerprint doorbell component
# R503 sensor connected via Serial2
fingerprint_doorbell:
  id: fp_doorbell
  touch_pin: GPIO5     # Touch ring input (white wire)
  doorbell_pin: GPIO19 # Output when no match (doorbell event)
  ignore_touch_ring: false

# Sensors
sensor:
  - platform: fingerprint_doorbell
    fingerprint_doorbell_id: fp_doorbell
    match_id:
      name: "Fingerprint Match ID"
      id: fp_match_id
    confidence:
      name: "Fingerprint Confidence"
      id: fp_confidence

text_sensor:
  - platform: fingerprint_doorbell
    fingerprint_doorbell_id: fp_doorbell
    match_name:
      name: "Fingerprint Match Name"
      id: fp_match_name

binary_sensor:
  - platform: fingerprint_doorbell
    fingerprint_doorbell_id: fp_doorbell
    ring:
      name: "Doorbell Ring"
      id: fp_ring
    finger:
      name: "Finger Detected"
      id: fp_finger

# Logging
logger:
  level: DEBUG
  logs:
    fingerprint_doorbell: DEBUG
