# Fingerprint Doorbell ESPHome Package
# Include this in your device configuration via packages:
#
#   packages:
#     fingerprint_doorbell: github://claudio-walser/esphome-fingerprint-doorbell/fingerprint-doorbell.yaml@main
#
# Required substitutions in your device config:
#   - api_encryption_key


# External components
external_components:
  - source:
      type: git
      url: https://github.com/claudio-walser/esphome-fingerprint-doorbell
      ref: main
    components: [ fingerprint_doorbell ]
    refresh: 0s

esphome:
  libraries:
    - "adafruit/Adafruit Fingerprint Sensor Library@^2.1.0"

# Web server for REST API endpoints
# REST API available at /fingerprint/*
#   GET  /fingerprint/list       - List all fingerprints
#   GET  /fingerprint/status     - Get sensor status
#   POST /fingerprint/enroll     - Start enrollment (?id=X&name=Y)
#   POST /fingerprint/cancel     - Cancel enrollment
#   POST /fingerprint/delete     - Delete fingerprint (?id=X)
#   POST /fingerprint/delete_all - Delete all fingerprints
#   POST /fingerprint/rename     - Rename fingerprint (?id=X&name=Y)

# Fingerprint doorbell component
# R503 sensor connected via Serial2 (GPIO16=RX, GPIO17=TX)
fingerprint_doorbell:
  id: fp_doorbell
  touch_pin: GPIO5     # Touch ring input (white wire)
  doorbell_pin: GPIO19 # Output when no match (doorbell event)
  ignore_touch_ring: false
  api_token: ${api_encryption_key}  # Protects REST API endpoints

# Sensors
sensor:
  - platform: fingerprint_doorbell
    fingerprint_doorbell_id: fp_doorbell
    match_id:
      name: "Fingerprint Match ID"
      id: fp_match_id
    confidence:
      name: "Fingerprint Confidence"
      id: fp_confidence

text_sensor:
  - platform: fingerprint_doorbell
    fingerprint_doorbell_id: fp_doorbell
    match_name:
      name: "Fingerprint Match Name"
      id: fp_match_name
    enroll_status:
      name: "Enrollment Status"
      id: fp_enroll_status
    last_action:
      name: "Last Action"
      id: fp_last_action

binary_sensor:
  - platform: fingerprint_doorbell
    fingerprint_doorbell_id: fp_doorbell
    ring:
      name: "Doorbell Ring"
      id: fp_ring
    finger:
      name: "Finger Detected"
      id: fp_finger
