# Example Home Assistant Automations for Fingerprint Doorbell
# These examples show how to use the fingerprint doorbell component

# ============================================
# AUTOMATIONS
# ============================================

automation:
  # Automation 1: Turn on light when specific person is detected
  - alias: "Front Door - John Unlocked"
    trigger:
      - platform: state
        entity_id: text_sensor.front_door_fingerprint_match_name
        to: "John"
    condition:
      - condition: numeric_state
        entity_id: sensor.front_door_fingerprint_confidence
        above: 100
    action:
      - action: light.turn_on
        target:
          entity_id: light.hallway
      - action: notify.mobile_app
        data:
          message: "John unlocked the front door"

  # Automation 2: Send notification when doorbell is rung
  - alias: "Front Door - Doorbell Ring"
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_doorbell_ring
        to: "on"
    action:
      - action: notify.mobile_app
        data:
          message: "Someone is at the front door"
          title: "Doorbell"
      - action: camera.snapshot
        target:
          entity_id: camera.front_door
        data:
          filename: "/config/www/doorbell_snapshot.jpg"

  # Automation 3: Unlock door for known fingerprints
  - alias: "Front Door - Auto Unlock"
    trigger:
      - platform: state
        entity_id: sensor.front_door_fingerprint_match_id
    condition:
      - condition: numeric_state
        entity_id: sensor.front_door_fingerprint_match_id
        above: 0
      - condition: numeric_state
        entity_id: sensor.front_door_fingerprint_confidence
        above: 150
    action:
      - action: lock.unlock
        target:
          entity_id: lock.front_door
      - action: notify.mobile_app
        data:
          message: "Door unlocked for {{ states('text_sensor.front_door_fingerprint_match_name') }}"

  # Automation 4: Monitor enrollment progress
  - alias: "Front Door - Enrollment Progress"
    trigger:
      - platform: state
        entity_id: text_sensor.front_door_enroll_status
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state not in ['', 'unknown'] }}"
    action:
      - action: notify.mobile_app
        data:
          message: "Fingerprint: {{ trigger.to_state.state }}"
          title: "Enrollment Status"

# ============================================
# SCRIPTS
# ============================================

script:
  # Script: Enroll new fingerprint via REST API
  # This uses the device's REST API endpoint
  enroll_fingerprint:
    alias: "Enroll New Fingerprint"
    fields:
      finger_id:
        description: "Fingerprint ID (1-200)"
        example: 1
      finger_name:
        description: "Name for this fingerprint"
        example: "John"
    sequence:
      - action: rest_command.enroll_fingerprint
        data:
          finger_id: "{{ finger_id }}"
          finger_name: "{{ finger_name }}"
      - action: notify.mobile_app
        data:
          message: "Enrolling fingerprint {{ finger_id }} for {{ finger_name }}. Place finger on sensor 5 times."

  # Script: Delete fingerprint via REST API
  delete_fingerprint:
    alias: "Delete Fingerprint"
    fields:
      finger_id:
        description: "Fingerprint ID to delete (1-200)"
        example: 1
    sequence:
      - action: rest_command.delete_fingerprint
        data:
          finger_id: "{{ finger_id }}"
      - action: notify.mobile_app
        data:
          message: "Deleted fingerprint ID {{ finger_id }}"

  # Script: Delete all fingerprints
  delete_all_fingerprints:
    alias: "Delete All Fingerprints"
    sequence:
      - action: rest_command.delete_all_fingerprints
      - action: notify.mobile_app
        data:
          message: "Deleted all fingerprints"

  # Script: Cancel enrollment
  cancel_enrollment:
    alias: "Cancel Enrollment"
    sequence:
      - action: rest_command.cancel_enrollment
      - action: notify.mobile_app
        data:
          message: "Enrollment cancelled"

# ============================================
# REST COMMANDS (add to configuration.yaml)
# ============================================
# These REST commands call the device's REST API endpoints
# Replace DEVICE_IP with your device's actual IP address

rest_command:
  enroll_fingerprint:
    url: "http://DEVICE_IP/fingerprint/enroll"
    method: POST
    payload: "id={{ finger_id }}&name={{ finger_name }}"
    content_type: "application/x-www-form-urlencoded"

  delete_fingerprint:
    url: "http://DEVICE_IP/fingerprint/delete"
    method: POST
    payload: "id={{ finger_id }}"
    content_type: "application/x-www-form-urlencoded"

  delete_all_fingerprints:
    url: "http://DEVICE_IP/fingerprint/delete_all"
    method: POST

  cancel_enrollment:
    url: "http://DEVICE_IP/fingerprint/cancel"
    method: POST

  rename_fingerprint:
    url: "http://DEVICE_IP/fingerprint/rename"
    method: POST
    payload: "id={{ finger_id }}&name={{ finger_name }}"
    content_type: "application/x-www-form-urlencoded"

# ============================================
# LOVELACE DASHBOARD EXAMPLE
# ============================================
# Add this to your Lovelace dashboard for easy management

# type: entities
# title: Front Door Fingerprint
# entities:
#   - entity: text_sensor.front_door_fingerprint_match_name
#     name: Last Match
#   - entity: sensor.front_door_fingerprint_match_id
#     name: Match ID
#   - entity: sensor.front_door_fingerprint_confidence
#     name: Confidence
#   - entity: binary_sensor.front_door_doorbell_ring
#     name: Doorbell
#   - entity: binary_sensor.front_door_finger_detected
#     name: Finger Detected
#   - entity: text_sensor.front_door_enroll_status
#     name: Enrollment Status
#   - entity: text_sensor.front_door_last_action
#     name: Last Action

# ============================================
# ALTERNATIVE: Using ESPHome Buttons + Actions
# ============================================
# Instead of REST API, you can define buttons in ESPHome YAML
# that use the built-in actions. Example ESPHome config:
#
# button:
#   - platform: template
#     name: "Enroll ID 1 - John"
#     on_press:
#       - fingerprint_doorbell.enroll:
#           finger_id: 1
#           name: "John"
#
#   - platform: template
#     name: "Cancel Enrollment"
#     on_press:
#       - fingerprint_doorbell.cancel_enroll
#
#   - platform: template
#     name: "Delete ID 1"
#     on_press:
#       - fingerprint_doorbell.delete:
#           finger_id: 1
#
#   - platform: template
#     name: "Delete All"
#     on_press:
#       - fingerprint_doorbell.delete_all
